[theme]
primaryColor = "#E30613"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FBF3F3"
textColor = "#1A1A1A"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[client]
showErrorDetails = false
